/* eslint-disable react-hooks/exhaustive-deps */
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useTranslation, Trans } from 'react-i18next';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import Cookies from 'js-cookie';
import Axios from 'axios';
import i18n from 'i18next';
import { I18nextProvider } from 'react-i18next';
import blog_pic from '../assets/blog.jpg'
import React, { useRef } from 'react';
import tunisia from '../assets/tunisia.png'
import togo from '../assets/togo.png'
import burkina_faso from '../assets/burkina-faso.png'
import mixer from '../assets/mixer.png'
import building from '../assets/building.png'

import { Slider } from '@/components';

export default function Home() {
  const router = useRouter();



  const { t, i18n } = useTranslation();
  const [loading, setLoading] = useState(true);
  const [blog, setBlog] = useState({})
  const [sliderWidth, setSliderWidth] = useState(550);
  const fetchBlogData = async () => {
    try {
      let blogEndpoint = "/api/post/getblogs";
      const response = await Axios.get(blogEndpoint);
      setBlog(response.data[0]);
      setLoading(false);
    } catch (error) {
      console.error("Error fetching blog data:", error);
      setLoading(false);
    }
  };

  useEffect(() => {
    const handleResize = () => {
      if (window.innerWidth <= 800) {
        setSliderWidth(window.innerWidth - 100);
      }

    };

    handleResize(); // Set initial width

    window.addEventListener('resize', handleResize);

    // Clean up the event listener
    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, []);

  // Listen for language changes and fetch blog data accordingly
  useEffect(() => {
    const onLanguageChange = (lang) => {
      console.log('Language changed:', lang);
      // Fetch the blog data again based on the new language
      if (loading) {
        fetchBlogData();
      }
    };

    // Subscribe to the 'languageChanged' event
    i18n.on('languageChanged', onLanguageChange);

    // Clean up the event listener when the component unmounts
    return () => {
      i18n.off('languageChanged', onLanguageChange);
    };
  }, []); // Empty dependency array to run it once

  useEffect(() => {
    const sections = document.querySelectorAll(`.${styles.fadeIn}`); // Use the specific class generated by CSS Modules
    const options = {
      threshold: 0.2, // Trigger when 20% of the section is visible
    };

    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add(styles['fade-in']); // Apply the fade-in animation class
        }
      });
    }, options);

    sections.forEach((section) => {
      observer.observe(section);
    });

    // Clean up the observer
    return () => {
      observer.disconnect();
    };
  }, []);

  return (
    <>
      <Head>
        <meta charset="utf-8" />
        <link rel="icon" href="../assets/logo.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="index,follow" />
        <meta name="theme-color" content="#000000" />
        <meta name="description" content="Group ETMHolding" />
        <link rel="icon" href="../assets/logo.png" />
        <title>Group ETM Holding</title>
      </Head>
      <div className={`${styles.header} fade-in`} >
        <h2 className='fade-in'>ETM Holding</h2>
        <p className='fade-in'>{t('header')}</p>
        <div className='button-filled'>
          <button className='fade-in' onClick={() => { router.push('/about') }}>{t('learn')}</button>
        </div>
      </div>
      <div className={`${styles.subheader} fade-in`} >
        <p className='fade-in'>{t('quote')}</p>
        <h5 className='fade-in'>Mohamed Traki - CEO ETM Holding</h5>
      </div>
      {!loading && (
        <div className={`${styles.last_container} fade-in`}>
          <div className={styles.last_container_header}>
            <h5 className='fade-in'>{t('last')}</h5>
          </div>
          <div className={styles.last__container_body} >
            <div className={styles.last__container_body}>
              {blog && blog?.image && (
                <Image src={blog?.image} alt='blog_pic' width={sliderWidth} height={350} />
              )}
            </div>
            <div className={styles.last__container_body_right}>
              <h5>{new Date(blog?.date).toDateString()}</h5>
              <h3>{blog?.title}</h3>
              <p dangerouslySetInnerHTML={{ __html: blog?.paragraph?.length > 250 ? blog?.paragraph?.substring(0, 250) + "..." : blog?.paragraph }} />
              <div className='dark__button'>
                <button onClick={() => { router.push(`/post/${blog?.id}`) }}>{t('read')}</button>
              </div>
            </div>
          </div>
        </div>
      )}
      {loading && (
        <h4>Article Loading...</h4>
      )}
      <div className={`${styles.fil__container} fade-in`}>
        <div className={styles.fil__container_items}>
          <div className={styles.fil__container_item}>
            <Image src={tunisia} alt='Tunisia' />
            <h5>{t('sub.tunisia')}</h5>
          </div>
          <div className={styles.fil__container_item}>
            <Image src={burkina_faso} alt='burkina_faso' />
            <h5>{t('sub.bur')}</h5>
          </div>
          <div className={styles.fil__container_item}>
            <Image src={togo} alt='togo' />
            <h5>{t('sub.togo')}</h5>
          </div>
          <div className={styles.fil__container_item}>
            <Image src={mixer} alt='Image' />
            <h5>{t('sub.beton')}</h5>
          </div>
          <div className={styles.fil__container_item}>
            <Image src={building} alt='Image' />
            <h5>{t('sub.imm')}</h5>
          </div>
        </div>
        <div className='dark__button'>
          <button onClick={() => { router.push('/filiales') }}>{t('sub.button')}</button>
        </div>
      </div>
      <Slider />
    </>
  )
}
